version: '3.3'

services:
  web:
    image: nginx
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf:z,ro
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=hackathon.arianb.me
    - NGINX_PORT=80
